name: simplePipeline

on:
  push:
    branches: [main]


jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          echo "Running Install Dependecies ..."
          npm install
      - name: Run Linting
        run: |
           echo "Running Linting tests ..."
          npm run lint
        env: 
          CI: true
